services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: artur
      POSTGRES_PASSWORD: chegur
      POSTGRES_DB: weather
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/weather
      DATABASE_USER: artur
      DATABASE_PASSWORD: chegur
    ports:
      - "8080:8080"

volumes:
  db-data: