services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: weather
    volumes:
      - db-data:/var/lib/postgresql@13/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_URL}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      API_TOKEN: ${API_TOKEN}
    ports:
      - "8080:8080"

volumes:
  db-data: